// 2-vue-state/src/App.vue
<script setup lang="ts">
import StateList from "./components/StateList.vue";
import StateNumber from "./components/StateNumber.vue";
import StateObject from "./components/StateObject.vue";
import TodoList from "./components/TodoList.vue";
</script>

<template>
  <!-- <StateNumber /> -->
  <!-- <StateObject /> -->
  <!-- <StateList></StateList> -->

  <TodoList></TodoList>
</template>

<style scoped></style>

// react/2-react-state-props/src/App.tsx
import "./App.css";
import { AddPerson } from "./components/AddPerson";
import { StateList } from "./components/StateList";
import { StateObject } from "./components/StateObject";

function App() {
  return (
    <>
      <AddPerson />
      <StateList />
      <StateObject />
    </>
  );
}

export default App;
