// vue/4-vue-props/src/components/MovieApp/Movies.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { IOmdbResponse } from "../../models/IOmdbResponse";
import { IMovie } from "../../models/IMovie";
import Movie from "./Movie.vue";

const movies = ref<IMovie[]>([]);

onMounted(async () => {
  const response = await fetch("https://omdbapi.com/?apikey=416ed51a&s=star");

  if (!response.ok) {
  }

  const data: IOmdbResponse = await response.json();

  // data = { Search: [...], totalResult: string, Response: string }
  movies.value = data.Search;
});

const handleBuy = (id: string) => {
  const foundMovie = movies.value.find((m) => m.imdbID === id);

  console.log("Du klickade på:", foundMovie?.Title);
};
</script>

<template>
  <div class="movies">
    <Movie
      v-for="movie in movies"
      :movie="movie"
      :key="movie.imdbID"
      @buy="handleBuy"
    />
  </div>
</template>

<style scoped>
.movies {
  display: flex;
  flex-direction: column;
}
</style>

// react/5-react-router/src/pages/Movies.tsx
import { useState } from "react";
import { IMovie } from "../models/IMovie";
import axios from "axios";
import { IOmdbResponse } from "../models/IOmdbResponse";
import { MovieSearch } from "../components/MovieSearch";
import { ShowMovies } from "../components/ShowMovies";
import { Spinner } from "../components/Spinner";

export const Movies = () => {
  const [movies, setMovies] = useState<IMovie[]>(
    JSON.parse(localStorage.getItem("movies") || "[]")
  );
  const [loading, setLoading] = useState(false);

  const getMovies = async (searchText: string) => {
    try {
      setLoading(true);
      const response = await axios.get<IOmdbResponse>(
        "https://omdbapi.com/?apikey=416ed51a&s=" + searchText
      );

      if (response.status !== 200) {
        throw new Error(JSON.stringify(response.data));
      }

      setMovies(response.data.Search);
      localStorage.setItem("movies", JSON.stringify(response.data.Search));
    } catch (error) {
      console.log("Ett fel inträffade: ", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <MovieSearch searchMovies={getMovies} />
      {loading && <Spinner></Spinner>}
      {!loading && (
        <>
          <h1>Movies</h1>
          <ShowMovies movies={movies}></ShowMovies>
        </>
      )}
    </>
  );
};
