// react/8-react-context/src/components/AddTodo.tsx
import { useContext, useState } from "react";
import { Button } from "./Button";
import { TodosContext } from "../contexts/TodosContext";

export const AddTodo = () => {
  const [userInput, setUserInput] = useState("");
  const { add } = useContext(TodosContext);

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        add(userInput);
        setUserInput("");
      }}
    >
      <input
        type="text"
        value={userInput}
        onChange={(e) => setUserInput(e.target.value)}
      />
      <Button click={() => {}}>
        <>Spara</>
      </Button>
    </form>
  );
};

// 3-vue-form-props/src/components/AddTodo.vue
<script setup lang="ts">
import { ref } from "vue";

const userInput = ref("");
const error = ref("");

const emit = defineEmits<{
  (e: "add", text: string): void;
}>();

const handleSubmit = () => {
  if (userInput.value !== "") {
    emit("add", userInput.value);
    userInput.value = "";
    error.value = "";
  } else {
    error.value = "Du måste fylla i någonting i textrutan";
  }
};
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" v-model="userInput" />
    <button>Spara</button>
  </form>
  <p v-if="error !== ''">{{ error }}</p>
</template>

<style scoped></style>
