// react/2-react-state-props/src/components/Todo/AddTodo.tsx
import { FormEvent, useState } from "react";

interface IAddTodoProps {
  addTodo: (text: string) => void;
}

export const AddTodo = (props: IAddTodoProps) => {
  const [userInput, setUserInput] = useState("");

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    props.addTodo(userInput);
  };

  return (
    <>
      <form onSubmit={handleSubmit}>
        <input
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
        />
        <button>Spara</button>
      </form>
    </>
  );
};

// 3-vue-form-props/src/components/AddTodo.vue
<script setup lang="ts">
import { ref } from "vue";

const userInput = ref("");
const error = ref("");

const emit = defineEmits<{
  (e: "add", text: string): void;
}>();

const handleSubmit = () => {
  if (userInput.value !== "") {
    emit("add", userInput.value);
    userInput.value = "";
    error.value = "";
  } else {
    error.value = "Du måste fylla i någonting i textrutan";
  }
};
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input type="text" v-model="userInput" />
    <button>Spara</button>
  </form>
  <p v-if="error !== ''">{{ error }}</p>
</template>

<style scoped></style>
