// vue/2-vue-state/src/components/StateObject.vue
<script setup lang="ts">
import { Person } from "@/models/Person";
import { ref } from "vue";

const p = ref<Person>(new Person("Sebastian", 44, true));

const change = () => {
  p.value.name = "Hanna";
};
</script>

<template>
  <div class="persons">
    <div class="person">
      <h3>{{ p.name }}</h3>
      <p>{{ p.age }}</p>
      <input type="checkbox" :checked="p.isMarried" />
    </div>
  </div>
  <button @click="change">Change</button>
</template>

// react/2-react-state-props/src/components/StateObject.tsx
import { useState } from "react";
import { Person } from "../models/Person";

export const StateObject = () => {
  const [person, setPerson] = useState<Person>(
    new Person("Sebastian", 44, true)
  );

  const handleClick = () => {
    console.log("Clickity");

    setPerson({ ...person, name: "Hanna" });
  };

  return (
    <>
      <h3>{person.name}</h3>

      <button onClick={handleClick}>Change name</button>
    </>
  );
};
