// 2-vue-state/src/components/StateList.vue
<script setup lang="ts">
import { Person } from "@/models/Person";
import { ref } from "vue";

const persons = ref<Person[]>([
  new Person("Sebastian", 44, true),
  new Person("Hanna", 44, true),
  new Person("Alvar", 13, false),
]);

const change = () => {
  persons.value.push(new Person("Astrid", 13, false));
};
</script>

<template>
  <div class="persons">
    <div class="person" v-for="(p, i) in persons" :key="i">
      <h3>{{ p.name }}</h3>
      <p>{{ p.age }}</p>
      <input type="checkbox" :checked="p.isMarried" />
    </div>
  </div>
  <button @click="change">Change</button>
</template>

// react/2-react-state-props/src/components/StateList.tsx
import { useState } from "react";
import { Person } from "../models/Person";

export const StateList = () => {
  const [persons, setPersons] = useState<Person[]>([
    new Person("Sebastian", 44, true),
    new Person("Hanna", 44, true),
  ]);

  const handleAdd = () => {
    setPersons([...persons, new Person("Lasse", 58, false)]);
  };

  const handleRemove = (person: Person) => {
    setPersons(persons.filter((p) => person.name !== p.name));
  };

  // const handleRemove = (i: number) => {
  //   const copy = [...persons];
  //   copy.splice(i, 1);
  //   setPersons(copy);
  // };

  const handleBirthday = (person: Person) => {
    setPersons(
      persons.map((p) => {
        if (p.name === person.name) {
          return { ...p, age: p.age + 1 };
        } else {
          return p;
        }
      })
    );
  };

  return (
    <>
      <button onClick={handleAdd}>Lägg till</button>

      {persons.map((p, i) => (
        <div key={i}>
          {p.name} - {p.age}
          <button
            onClick={() => {
              handleRemove(p);
            }}
          >
            Ta bort
          </button>
          <button onClick={() => handleBirthday(p)}>Fyll år</button>
        </div>
      ))}
    </>
  );
};
